version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.0
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: "16.13.2"
      - checkout
      - aws-cli/setup
      - eb/setup
      # install dependencies in both apps
      - restore_cache:
          key: v1-deps-{{ checksum "udagram-api/package-lock.json" }}
      - run:
          name: Installing Backend
          command: |
            npm run backend:install
      - save_cache:
          key: v1-deps-{{ checksum "udagram-api/package-lock.json" }}
          paths: 
            - udagram-api/node_modules   
      - restore_cache:
          key: v1-deps-{{ checksum "udagram-frontend/package-lock.json" }}
      - run:
          name: Installing Frontend
          command: |
            npm run frontend:install
      - save_cache:
          key: v1-deps-{{ checksum "udagram-frontend/package-lock.json" }}
          paths: 
            - udagram-frontend/node_modules  
      - run:
          name: Building Backend
          command: |
            npm run backend:build
      - run:
          name: Building Frontend
          command: |
            npm run frontend:build
      - run:
          name: Deploying Frontend
          command: |
            npm run frontend:deploy
      - run:
          name: Deploying Backend
          command: |
            npm run backend:deploy
      - run:
          name: Afterall
          command: echo "All-Done"

